export interface RealUniversityData {
  id: string;
  rank: number;
  name: string;
  country: string;
  city: string;
  qsRank: string;
  theRank: string;
  type: string;
  yearEstablished: number;
  website: string;
  academicReputation: string;
  employerReputation: string;
  facultyStudentRatio: string;
  citationsPerFaculty: string;
  internationalFaculty: string;
  internationalStudents: string;
  tuitionFee?: number;
}

export const REAL_UNIVERSITIES: RealUniversityData[] = [
  {
    id: "pku",
    rank: 1,
    name: "Peking University",
    country: "China",
    city: "Beijing",
    qsRank: "14",
    theRank: "13",
    type: "Public",
    yearEstablished: 1898,
    website: "https://www.pku.edu.cn",
    academicReputation: "NA",
    employerReputation: "NA",
    facultyStudentRatio: "10.2:1",
    citationsPerFaculty: "NA",
    internationalFaculty: "15%",
    internationalStudents: "15.10%",
    tuitionFee: 5000
  },
  {
    id: "tsinghua",
    rank: 2,
    name: "Tsinghua University",
    country: "China",
    city: "Beijing",
    qsRank: "17",
    theRank: "12",
    type: "Public",
    yearEstablished: 1911,
    website: "https://www.tsinghua.edu.cn",
    academicReputation: "NA",
    employerReputation: "NA",
    facultyStudentRatio: "11.5:1",
    citationsPerFaculty: "NA",
    internationalFaculty: "20%",
    internationalStudents: "13.60%",
    tuitionFee: 4800
  },
  {
    id: "fudan",
    rank: 3,
    name: "Fudan University",
    country: "China",
    city: "Shanghai",
    qsRank: "30",
    theRank: "36",
    type: "Public",
    yearEstablished: 1905,
    website: "https://www.fudan.edu.cn",
    academicReputation: "NA",
    employerReputation: "NA",
    facultyStudentRatio: "11.1:1",
    citationsPerFaculty: "NA",
    internationalFaculty: "12%",
    internationalStudents: "22.20%",
    tuitionFee: 5500
  },
  {
    id: "sjtu",
    rank: 4,
    name: "Shanghai Jiao Tong University",
    country: "China",
    city: "Shanghai",
    qsRank: "45",
    theRank: "52",
    type: "Public",
    yearEstablished: 1896,
    website: "https://en.sjtu.edu.cn",
    academicReputation: "NA",
    employerReputation: "NA",
    facultyStudentRatio: "11.3:1",
    citationsPerFaculty: "NA",
    internationalFaculty: "10%",
    internationalStudents: "14.90%",
    tuitionFee: 6200
  },
  {
    id: "zju",
    rank: 5,
    name: "Zhejiang University",
    country: "China",
    city: "Hangzhou",
    qsRank: "47",
    theRank: "47",
    type: "Public",
    yearEstablished: 1897,
    website: "https://www.zju.edu.cn/english",
    academicReputation: "NA",
    employerReputation: "NA",
    facultyStudentRatio: "11.8:1",
    citationsPerFaculty: "NA",
    internationalFaculty: "9%",
    internationalStudents: "12.30%",
    tuitionFee: 4900
  },
  {
    id: "nju",
    rank: 6,
    name: "Nanjing University",
    country: "China",
    city: "Nanjing",
    qsRank: "120",
    theRank: "95",
    type: "Public",
    yearEstablished: 1902,
    website: "https://www.nju.edu.cn",
    academicReputation: "88",
    employerReputation: "86",
    facultyStudentRatio: "14:1",
    citationsPerFaculty: "82",
    internationalFaculty: "14%",
    internationalStudents: "16%"
  },
  {
    id: "ustc",
    rank: 7,
    name: "USTC",
    country: "China",
    city: "Hefei",
    qsRank: "130",
    theRank: "80",
    type: "Public",
    yearEstablished: 1958,
    website: "https://en.ustc.edu.cn/",
    academicReputation: "88",
    employerReputation: "86",
    facultyStudentRatio: "14:1",
    citationsPerFaculty: "82",
    internationalFaculty: "14%",
    internationalStudents: "16%"
  },
  {
    id: "whu",
    rank: 8,
    name: "Wuhan University",
    country: "China",
    city: "Wuhan",
    qsRank: "180",
    theRank: "160",
    type: "Public",
    yearEstablished: 1893,
    website: "https://www.whu.edu.cn",
    academicReputation: "88",
    employerReputation: "86",
    facultyStudentRatio: "14:1",
    citationsPerFaculty: "82",
    internationalFaculty: "14%",
    internationalStudents: "16%"
  },
  {
    id: "tongji",
    rank: 10,
    name: "Tongji University",
    country: "China",
    city: "Shanghai",
    qsRank: "190",
    theRank: "185",
    type: "Public",
    yearEstablished: 1907,
    website: "https://www.tongji.edu.cn",
    academicReputation: "88",
    employerReputation: "86",
    facultyStudentRatio: "14:1",
    citationsPerFaculty: "82",
    internationalFaculty: "14%",
    internationalStudents: "16%"
  },
  {
    id: "bnu",
    rank: 11,
    name: "Beijing Normal University",
    country: "China",
    city: "Beijing",
    qsRank: "247",
    theRank: "134",
    type: "Public",
    yearEstablished: 1902,
    website: "https://www.bnu.edu.cn/",
    academicReputation: "38.4",
    employerReputation: "6.8",
    facultyStudentRatio: "1:07",
    citationsPerFaculty: "7.4",
    internationalFaculty: "1.20%",
    internationalStudents: "10.20%",
    tuitionFee: 8000
  },
  {
    id: "hust",
    rank: 12,
    name: "Huazhong University of Science and Technology",
    country: "China",
    city: "Wuhan",
    qsRank: "319",
    theRank: "158",
    type: "Public",
    yearEstablished: 1952,
    website: "https://www.hust.edu.cn/",
    academicReputation: "22.7",
    employerReputation: "29.2",
    facultyStudentRatio: "1:06",
    citationsPerFaculty: "8.9",
    internationalFaculty: "5.50%",
    internationalStudents: "7.10%",
    tuitionFee: 5400
  },
  {
    id: "xianjiao",
    rank: 13,
    name: "Xi'an Jiaotong University",
    country: "China",
    city: "Xi'an",
    qsRank: "295",
    theRank: "251-300",
    type: "Public",
    yearEstablished: 1896,
    website: "https://www.xjtu.edu.cn/",
    academicReputation: "28.5",
    employerReputation: "44.2",
    facultyStudentRatio: "1:06",
    citationsPerFaculty: "12.8",
    internationalFaculty: "5.80%",
    internationalStudents: "8.60%",
    tuitionFee: 5100
  },
  {
    id: "sysu",
    rank: 14,
    name: "Sun Yat-sen University",
    country: "China",
    city: "Guangzhou",
    qsRank: "331",
    theRank: "201-250",
    type: "Public",
    yearEstablished: 1924,
    website: "https://www.sysu.edu.cn/",
    academicReputation: "36.4",
    employerReputation: "22.3",
    facultyStudentRatio: "1:07",
    citationsPerFaculty: "8.1",
    internationalFaculty: "3.90%",
    internationalStudents: "6.50%",
    tuitionFee: 4300
  }
];
