"""add documents to faculty student nominations

Revision ID: 12f09798b0d6
Revises: f01dea7816e2
Create Date: 2026-07-15 11:34:42.973449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12f09798b0d6'
down_revision: Union[str, Sequence[str], None] = 'f01dea7816e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty_student_nominations', sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculty_student_nominations', 'documents')
    # ### end Alembic commands ###
