"""Initial schema

Revision ID: 88d50ea9303d
Revises: 
Create Date: 2026-06-27 11:05:46.709890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88d50ea9303d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('subregion', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('focus', sa.String(length=30), nullable=True),
    sa.Column('research_level', sa.String(length=30), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('total_faculty', sa.Integer(), nullable=True),
    sa.Column('avg_fees', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('placement_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=300), nullable=True),
    sa.Column('campus_photo', sa.String(length=300), nullable=True),
    sa.Column('has_medicine', sa.Boolean(), nullable=True),
    sa.Column('has_scholarship', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_universities_country'), 'universities', ['country'], unique=False)
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('admission_details',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('admission_process', sa.Text(), nullable=True),
    sa.Column('entrance_exams', sa.String(length=200), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('minimum_gpa', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admission_details_university_id'), 'admission_details', ['university_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('degree_type', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('fees', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_university_id'), 'courses', ['university_id'], unique=False)
    op.create_table('ranking_scores',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(precision=2), nullable=True),
    sa.Column('ar_score', sa.Float(), nullable=True),
    sa.Column('er_score', sa.Float(), nullable=True),
    sa.Column('fsr_score', sa.Float(), nullable=True),
    sa.Column('irn_score', sa.Float(), nullable=True),
    sa.Column('cpp_score', sa.Float(), nullable=True),
    sa.Column('ppf_score', sa.Float(), nullable=True),
    sa.Column('swp_score', sa.Float(), nullable=True),
    sa.Column('ifr_score', sa.Float(), nullable=True),
    sa.Column('isr_score', sa.Float(), nullable=True),
    sa.Column('inbound_score', sa.Float(), nullable=True),
    sa.Column('outbound_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university_id', 'year', name='uq_university_year')
    )
    op.create_index(op.f('ix_ranking_scores_university_id'), 'ranking_scores', ['university_id'], unique=False)
    op.create_index(op.f('ix_ranking_scores_year'), 'ranking_scores', ['year'], unique=False)
    op.create_table('saved_universities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'university_id', name='uq_user_university')
    )
    op.create_index(op.f('ix_saved_universities_university_id'), 'saved_universities', ['university_id'], unique=False)
    op.create_index(op.f('ix_saved_universities_user_id'), 'saved_universities', ['user_id'], unique=False)
    op.create_table('university_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('research_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('placement_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('faculty_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_metrics_university_id'), 'university_metrics', ['university_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_university_metrics_university_id'), table_name='university_metrics')
    op.drop_table('university_metrics')
    op.drop_index(op.f('ix_saved_universities_user_id'), table_name='saved_universities')
    op.drop_index(op.f('ix_saved_universities_university_id'), table_name='saved_universities')
    op.drop_table('saved_universities')
    op.drop_index(op.f('ix_ranking_scores_year'), table_name='ranking_scores')
    op.drop_index(op.f('ix_ranking_scores_university_id'), table_name='ranking_scores')
    op.drop_table('ranking_scores')
    op.drop_index(op.f('ix_courses_university_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_admission_details_university_id'), table_name='admission_details')
    op.drop_table('admission_details')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.drop_index(op.f('ix_universities_country'), table_name='universities')
    op.drop_table('universities')
    # ### end Alembic commands ###
