"""add faculty student nominations table

Revision ID: f01dea7816e2
Revises: 94f9f1706fe8
Create Date: 2026-07-15 11:02:57.833612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01dea7816e2'
down_revision: Union[str, Sequence[str], None] = '94f9f1706fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_student_nominations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('submitted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('nominee_name', sa.String(), nullable=False),
    sa.Column('nominee_email', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faculty_student_nominations')
    # ### end Alembic commands ###
